[tools]
act = "0.2.84"
gh = "2.87.3"
jq = "1.8.1"
"pipx:keyring" = { version = "25.7.0", uvx_args = "--with keyrings.google-artifactregistry-auth" }
trivy = "0.69.2"
uv = "0.10.2"

[settings]
lockfile = true # Pins exact versions and checksums of tools
python.uv_venv_auto = "create|source"

# tools can read the versions files used by other version managers
idiomatic_version_file_enable_tools = [
  "python", # .python-version stores python version being used
]

[task_config]
includes = [
  "tasks.toml",
  ".mise/tasks",
]
