sonar.projectKey=aignostics_tme-studio2
sonar.organization=aignostics
sonar.projectVersion=0.0.0
sonar.projectDescription=🎨 A toolkit to explore the Aignostics OpenTME dataset.
sonar.links.homepage=https://github.com/aignostics/tme-studio
sonar.links.scm=https://github.com/aignostics/tme-studio
sonar.links.ci=https://github.com/aignostics/tme-studio/actions
sonar.links.issues=https://github.com/aignostics/tme-studio/issues
sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.python.version=3.11, 3.12, 3.13
sonar.coverage.exclusions=noxfile.py, template/**, tests/**, docs/**, dist/**
sonar.exclusions=template/**, docs/**, dist/**, **/notebooks/**
