name: 'Run Tests'
description: 'Run tests'

inputs:
  test-type:
    description: 'Type of test (unit, integration, e2e, long-running)'
    required: true
  mise-task:
    description: 'Mise task to execute'
    required: true
  skip-marker:
    description: 'Commit message or PR label marker to skip this test'
    required: false
  commit-message:
    description: 'The commit message to check for skip markers'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run tests
      if: |
        (inputs.skip-marker == '' || (
          !contains(inputs.commit-message, inputs.skip-marker) &&
          !contains(github.event.pull_request.labels.*.name, inputs.skip-marker)
        )) &&
        (!contains(inputs.commit-message, 'skip:test:all')) &&
        (!contains(github.event.pull_request.labels.*.name, 'skip:test:all'))
      env:
        MISE_TASK: ${{ inputs.mise-task }}
      shell: bash
      run: |
        mise run "${MISE_TASK}"
