name: "Lint"

on:
  workflow_call:
    # No inputs needed at this time
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER:
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Setup Dev Environment
        uses: ./.github/actions/setup-dev-env
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Lint
        run: mise run lint
