name: "Publish Package"

on:
  workflow_call: {}


jobs:
  package_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

      - name: Initialize mise and install Python dependencies
        run: mise run install

      - name: Build documentation
        run: mise run docs

      - name: Build distribution
        run: uv build

      - name: Have audit checks publish to reports/ for auditing
        run: mise run audit

      - name: Generate release notes
        shell: bash
        run: |
          if [ -f "CHANGELOG.md" ]; then
            awk '/^## / {if (++count == 2) exit} count == 1' CHANGELOG.md >> RELEASE_NOTES.md
          fi
          if [ ! -s "RELEASE_NOTES.md" ]; then
            echo "No release notes available." >> RELEASE_NOTES.md
          fi
          echo "" >> RELEASE_NOTES.md

      - name: Publish distribution to PyPI
        run: uv publish

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} ./dist/* ./reports/* \
            --notes-file RELEASE_NOTES.md \
            --title "${{ github.ref_name }}"
