name: lint-workflows

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  lint-workflows:
    name: Lint workflow files
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check action pins
        id: pinact
        continue-on-error: true
        uses: suzuki-shunsuke/pinact-action@896d595f299e71d65b9d28349d6956abe144390a # v3.0.0
        with:
          review: "true"
          skip_push: "true"
          github_token_for_review: ${{ github.token }}
          reviewdog_filter_mode: added

      - name: Lint with actionlint
        id: actionlint
        continue-on-error: true
        uses: reviewdog/action-actionlint@dbe5299849118fd6f099ba563d263d770955a64a # v1.73.2
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review
          filter_mode: added
          fail_on_error: "true"

      - name: Fail if any linter reported errors
        if: steps.pinact.outcome == 'failure' || steps.actionlint.outcome == 'failure'
        run: exit 1
